import { Poppins } from "next/font/google";
import "./globals.css";
import Head from "next/head";
const poppins = Poppins({ subsets: ["latin"],
weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
 });

export const metadata = {
  title: "Buza Cristian | Web Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
          <link rel="shortcut icon" href="/favicon.ico" />
    </Head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
